### ISSUE TITLE
Output format names are somewhat confusing

### ISSUE THREAD

**Issue by erickrf** [Unbabel/OpenKiwi#15]
The options for defining the output formats, `wmt18` and `wmt17`, can be somewhat confusing. I think something like `with-gaps` would be clearer, especially to newcomers to QE.

This is particularly misleading when running an evaluate config on source tags. If set to `wmt18`, the script will interpret that there are gap tags in the system output, which was not the case in WMT 2018.

**Comment by daandouwe** [comment]
Closed because resoled with Kiwi v2.
