### ISSUE TITLE
Combining NuQE predictions for words and gaps

### ISSUE THREAD

**Issue by erickrf** [Unbabel/OpenKiwi#20]
When running NuQE predict, it outputs either target word tags or gap tags. In my workflow, I have to run a script afterwards to merge both correctly. Besides that, it outputs the binary tag probability instead of the tags themselves. 

It would be great if there were a way to:
- run two NuQE models, one for words and the other for gaps, and it took care of merging the outputs.
- choose either tags or probabilities in the output

**Comment by daandouwe** [comment]
Close because no longer applicable.
