### ISSUE TITLE
Where is ape-qe and all its files?

### ISSUE THREAD

**Issue by BonjourDeutsch** [Unbabel/OpenKiwi#26]
There are six files in directory "models":
    linear_word_qe_classifier.py -> linear model
    nuqe.py -> nuqe model
    predictor.py -> predictor part of predictor-estimator model
    predictor_estimator.py -> estimator part of predictor-esitmator model
    quetch.py -> quetch model
    utils.py -> all kinds of tools
    model.py -> the inlet to all models 
But there is not a file accords to ape-qe model!
And the same to other directories, where I can find files for nuqe\predest\quetch\linear, but no one is for ape-qe! Not any one!
Where the hell is ape-qe and all its related files? Or did I misunderstand something?

**Comment by BonjourDeutsch** [comment]
Thank you so much for your explanation. @captainvera 
Now I know what I should do. Thank you a lot.

**Comment by captainvera** [comment]
You are welcome, let me know if you have any other doubts! 
I'm closing this issue for now.
