### ISSUE TITLE
Hi, I am trying to load the model once and then predict to stdout as the input is fed to stdin. I cannot find any module in the python package to do this.

### ISSUE THREAD

**Issue by Bhavani01** [Unbabel/OpenKiwi#54]

**Comment by captainvera** [comment]
Hey @Bhavani01,

We have no specific module for doing this. You would have to write a wrapper to our prediction interface to do this. You can find the documentation for our Python API, [here](https://unbabel.github.io/OpenKiwi/source/kiwi.predictors.html#module-kiwi.predictors.predictor). Note: Mind you I just spotted a small typo in our docs, the example should be a dict and not a list. 

 You would need to have a python scripts that loads the model once, and then continuously reads from stdin and creates the dicts as shown in the documentation.

**Comment by Bhavani01** [comment]
Hi,
If we modiy the code to enable this, would you be willing to accept a pull request with the changes?
Thanks
Bhavani

**Comment by captainvera** [comment]
Hey, 
yes of course. As long as these things are done according to these [guidelines](https://github.com/Unbabel/OpenKiwi/blob/master/CONTRIBUTING.MD) we encourage contributions!

**Comment by daandouwe** [comment]
Closed due to inactivity.
