### ISSUE TITLE
how fast is the predictor training supposed to be?

### ISSUE THREAD

**Issue by BigBorg** [Unbabel/OpenKiwi#55]
I'm training predictor model on 10 million sentence pairs using gpu. Sentence length is limited to 1 to 50. Batch size is 128. According to the log, training for an epoch should taka about a day. Is this performance normal? What is the most time consuming nn layer?

**Comment by captainvera** [comment]
To answer the question on the title of the issue: Not very fast. 

That performance sounds about right. Performance was never the focus of the development of Openkiwi, especially training performance. To be honest I've never really profiled the performance of training a Kiwi model. I'd be *Very* interested in the results if you do so! 

We are currently working on a refactor of kiwi which should bring several improvements on this front: Multi-gpu, multi-threaded data loading, etc

Stay tuned for more news on that!

**Comment by captainvera** [comment]
Closing. Feel free to open another issue in case you have questions
