### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by mzeidhassan** [Unbabel/OpenKiwi#57]
Hello OpenKiwi team,
First, thanks for providing such good framework. It looks promising.

I have a question since I am a bit confused:

I only have source and target data (corpus.en, corpus.es). Is this enough to train a model? As far as I could understand from going through some threads, this should be enough to create a 'predictor' model, and maybe the predictor model can be used to train an 'estimator' model if you have some post-edited data later, right?

If right, in such case, I should only have the following lines under DATA OPTS in the [config file](https://github.com/Unbabel/OpenKiwi/blob/master/experiments/train_predictor.yaml):

```
### DATA OPTS ###

# Source and Target Files
train-source: data/parallel/corpus.en
train-target: data/parallel/corpus.es
```

Are there any other changes that I need to make?

I would be grateful if you can give guidance on best practices of creating a model using only source and target data.

Thanks in advance for your support!

**Comment by captainvera** [comment]
Hi @mzeidhassan, 

First of all, I'm sorry for my delayed response. What you are saying is absolutely correct. Be mindful however, that the predictor model is not an actual QE model (it cannot predict TER or word tags). It is merely a pretraining step or in other words, the first part of a two-part model the Predictor-Estimator. 
The estimator is plugged on top of the predictor and uses the embeddings learned by the predictor to predict the actual QE tags. That said, the changes you propose to the config are absolutely correct. 

Let me know if you have any other questions.

**Comment by mzeidhassan** [comment]
Thank you so much for your support @captainvera 
I appreciate it.

**Comment by captainvera** [comment]
hey @mzeidhassan can I close this issue?

**Comment by mzeidhassan** [comment]
Thank you @captainvera for your kind follow-up. I am closing it now. Thanks again!
