### ISSUE TITLE
I have use quickstart .

### ISSUE THREAD

**Issue by cyjack** [Unbabel/OpenKiwi#66]
but i don't know how to give sentence score .dose it need word-leval score before do that .I use wmt2020 model from kiwi as the baseline.
http://www.statmt.org/wmt20/quality-estimation-task.html
the model execute but just give me that 
{'batch_size': 64,
 'config': 'predict_estimator.yaml',
 'debug': False,
 'experiment_name': 'predict-predest',
 'gpu_id': 0,
 'load_data': None,
 'load_model': 'best_model.torch',
 'load_vocab': None,
 'log_interval': 100,
 'mlflow_always_log_artifacts': False,
 'mlflow_tracking_uri': 'mlruns/',
 'model': 'estimator',
 'output_dir': 'peace&love',
 'quiet': False,
 'run_name': None,
 'run_uuid': None,
 'save_config': None,
 'save_data': None,
 'seed': 42}
Local output directory is: peace&love
Predict with the PredEst (Predictor-Estimator) model
{'batch_size': 64,
 'config': 'predict_estimator.yaml',
 'debug': False,
 'experiment_name': 'predict-predest',
 'gpu_id': -1,
 'load_data': None,
 'load_model': 'best_model.torch',
 'load_vocab': None,
 'log_interval': 100,
 'mlflow_always_log_artifacts': False,
 'mlflow_tracking_uri': 'mlruns/',
 'model': 'estimator',
 'output_dir': 'peace&love',
 'quiet': False,
 'run_name': None,
 'run_uuid': None,
 'save_config': None,
 'save_data': None,
 'seed': 42}
Local output directory is: peace&love
Predict with the PredEst (Predictor-Estimator) model
Loaded vocabularies from best_model.torch
Is it wrong ,so stop?

**Comment by captainvera** [comment]
Sorry, I didn't see this issue earlier. 

Do you mind sharing your `predict_estimator.yaml` file?

**Comment by daandouwe** [comment]
Closed due to inactivity.
