### ISSUE TITLE
Hyperparamete tuning using skorch

### ISSUE THREAD

**Issue by danparamov** [Unbabel/OpenKiwi#67]
Hello, I am trying to use Random Search for hyperparameter tuning using skorch. I am using RandomSearchCV to find the best hyperparameters when running my estimator yaml file, however because there are many wrappers, I can't get it to work.

My question is more general, do you have any experience with this? or might you know someone who has experience with this?

Thank you.

**Comment by captainvera** [comment]
Hey Dan, 

I'm really sorry but I missed this issue! 
Did you Make any progress with this? I would be very interested in knowing your results!

From our end, we have successfully implemented Hyper-parameter search on Kiwi, but using a library called [Optuna](https://optuna.org).

I can provide an example script if you're interested.

**Comment by danparamov** [comment]
Hi Miguel,

Sorry for the late reply.

To tell you the truth, I haven't been able to make it work using skorch. I
would love to get your take on it, here is the code
<https://github.com/danparamov/Quality_Estimation_WMT20> I have implemented
to do the random search on kiwi.

Please let me know if you have any questions. It will be great if we can
meet and discuss about this one of these days, let me know your thoughts.

Thank you,

Daniel Paramo
