### ISSUE TITLE
Error happened when running demo

### ISSUE THREAD

**Issue by iamhere1** [Unbabel/OpenKiwi#81]
**Describe the bug**
When I run the demo according to "https://unbabel.github.io/OpenKiwi/usage.html", 
I run the folloing script,   
" from kiwi.lib.train import train_from_file "
then error happend:

![image](https://user-images.githubusercontent.com/8308024/98636088-1c634600-2361-11eb-8f2d-d3bf0db9272b.png)

**To Reproduce**
1. python
2. from kiwi.lib.train import train_from_file

**Environment (please complete the following information):**
 - OS: mac
 - OpenKiwi version:  latest code from master
 - Python version:  3.6.10

**Comment by daandouwe** [comment]
Hey @iamhere1,

Unfortunately, (for this reason ;)) OpenKiwi is not supported with Python<3.7. Could you try to reinstall with Python 3.7 or 3.8 and try again?

**Comment by iamhere1** [comment]
Hi @deandouwe,  
Thank you for your replay. I'm sorry to reply so late. I have some urgent matters to deal with these two days. I have tried to use python 3.7.9,  this problem disappeared. Howerver, another problem appeared, do I need to install some pakage to solve this?
![Uploading image.png…]()

**Comment by daandouwe** [comment]
No problem! Oh that's a strange error - Transformers is a core package for OpenKiwi.

I just checked and it is in the dependencies (it did not disappear all of a sudden, that would have been very bad 😅 ): https://github.com/Unbabel/OpenKiwi/blob/master/pyproject.toml#L40

Did you maybe get an error when installing? Are you installing using poetry or using pip?

A quick solution for your problem (and maybe a check if the installation went right) is to 
```bash
pip install -U transformers
```
But best to try to reinstall OpenKiwi first, to see if there is an error.

**Comment by daandouwe** [comment]
Did you solve the issue? I can't see the message anymore.

**Comment by iamhere1** [comment]
hi @daandouwe,
Thank you very much. I'm sorry to reply so late. I have some urgent matter to deal with these two days. 
I tried using python 3.7,  and installed some pakages, now it works. 
Thank again for your help!

**Comment by iamhere1** [comment]
> No problem! Oh that's a strange error - Transformers is a core package for OpenKiwi.
> 
> I just checked and it is in the dependencies (it did not disappear all of a sudden, that would have been very bad 😅 ): https://github.com/Unbabel/OpenKiwi/blob/master/pyproject.toml#L40
> 
> Did you maybe get an error when installing? Are you installing using poetry or using pip?
> 
> A quick solution for your problem (and maybe a check if the installation went right) is to
> 
> ```shell
> pip install -U transformers
> ```
> 
> But best to try to reinstall OpenKiwi first, to see if there is an error.

Yeah, I did this and it is solved now,  Thank you.

**Comment by daandouwe** [comment]
Nice that it's now working!

But you steel needed to do an additional manual install of transformers?

**Comment by iamhere1** [comment]
> Nice that it's now working!
> 
> But you steel needed to do an additional manual install of transformers?

Yeah, thank you very much!  And thank you for the great contribution!
