### ISSUE TITLE
openkiwi version

### ISSUE THREAD

**Issue by leileilin** [Unbabel/OpenKiwi#93]
**Describe the bug**
when i use command pip install opnekiwi, and then i check the version of openkiwi, it is just 0.1.3. But I think there is already version 2.0.0. so anyone can tell me what cause that ?
Thank you.

**Comment by zhaofuchen** [comment]
firstly you can uninstall openkiwi：
          pip uninstall openkiwi
then try to use command：
         pip install openkiwi==2.1.0

**Comment by leileilin** [comment]
> firstly you can uninstall openkiwi：
> pip uninstall openkiwi
> then try to use command：
> pip install openkiwi==2.1.0

i have tried the above comand, it will cause error which is Could not find a version
